name: responsive_dialog
description: A new Flutter package project.
version: 0.2.4
homepage: https://www.app-logik.de/
repository: https://github.com/applogik/responsive_dialog

environment:
  sdk: '>=2.18.1'
  flutter: '>=2.12.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
